### ISSUE TITLE
Unable to build the dextool in ubuntu

### ISSUE THREAD

**Issue by haruming** [joakim-brannstrom/dextool#1122] opened 2020-06-19 01:44 UTC
Hi, I have difficulty in building the dextool by myself.
I tried using this commands

`git clone https://github.com/joakim-brannstrom/dextool.git
cd dextool
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/path/to/where/to/install/dextool/binaries ..
make install -j2`

after that I got an error saying
![image](https://user-images.githubusercontent.com/16981363/85087879-45980400-b211-11ea-996a-729560222dd4.png)
I have no idea how to fix this after searching in Google. It seems like there are some bugs in the dextool/sumtype.
Correct me if i am wrong, thank you!

**Comment by joakim-brannstrom** [comment] 2020-06-19 15:31
Thank you for the report. I will look into it tomorrow

**Comment by joakim-brannstrom** [comment] 2020-06-21 22:19
I think the problem may have to do with dextool not being compatible with older D compilers. What version of the compiler did you use?

**Comment by haruming** [comment] 2020-06-22 11:22
Hi, I am using a D compiler v2.092.1

**Comment by joakim-brannstrom** [comment] 2020-06-23 20:14
I have been unable to reproduce the problem. Did you use the master branch or the latest official release?

**Comment by joakim-brannstrom** [comment] 2020-06-23 21:33
I see, you tried to compile master from the command you wrote. Hmm, I am lost as to what the problem may be. Could you maybe try to run this make command:

```sh
make install -j2 VERBOSE=1
```

because then I can see what the actual arguments are to the compiler.

**Comment by pokgak** [comment] 2020-08-16 15:21
Did you used the exact command above? If the answer is yes I can see why it might not work. As part of the command you wrote `-DCMAKE_INSTALL_PREFIX=/path/to/where/to/install/dextool/binaries`, which most likely will not exists on your system :)

I built from master today and also cannot reproduce this.

**Comment by joakim-brannstrom** [comment] 2020-08-16 15:57
I'll close the issue. Open if it still persistent.

**Closed** 2020-08-16 15:57 UTC
