### ISSUE TITLE
Impossible to change mutant using arrowkeys

### ISSUE THREAD

**Issue by JKRT** [joakim-brannstrom/dextool#914] opened 2019-09-15 20:04 UTC
On my system. Using Firefox I am unable to change between mutants

![bild](https://user-images.githubusercontent.com/8775827/64926980-b171ba00-d804-11e9-9bb4-d0e8313cd731.png)

Talking to Niklas it seems that it works for him on Firefox

**Comment by JKRT** [comment] 2019-09-15 20:06
I am using Mozilla Firefox 68.0.1 and X11

**Comment by joakim-brannstrom** [comment] 2019-09-15 20:16
Hmm it works for me in 68.0.2 and X11. You didn't have something else in focus?

**Comment by JKRT** [comment] 2019-09-16 12:10
Nope. However, it is a bit more special since I use Ubuntu via Windows WSL and forward it to an X11 server... I do not think that there are that many people who have my use case. Add a won't fix and close it. IFF someone else would have this issue I think it can be reopened

**Comment by peatersson** [comment] 2019-09-16 14:15
I think that closing the issue as "wont fix" is reasonable, since on every other system I have tested it on it worked as intended. 

As you said @JKRT,  your use case might be one where it just doesn't work. Maybe we can wait and test it on the university computers, and then we'll know if a fix is required or not?

**Comment by joakim-brannstrom** [comment] 2019-09-16 14:49
I see, that may explain it. I'll wait until either of you have confirmed that it works at uni.

**Comment by peatersson** [comment] 2019-09-19 10:44
Tested and confirmed to work on uni-computers.

**Closed** 2019-09-19 10:53 UTC
